include: package:flutter_lints/flutter.yaml

plugins:
  riverpod_lint: ^3.1.3

linter:
  rules:
    - annotate_overrides
    - prefer_final_fields
    - prefer_single_quotes
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_constructors_in_immutables
    - prefer_const_literals_to_create_immutables