name: pocket_ville
description: "The practical encyclopedia for trainers, at your fingertips"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.11.0

dependencies:
  cached_network_image_ce: ^4.6.0
  dio: ^5.9.1
  dio_cache_interceptor: ^4.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.3
  freezed_annotation: ^3.1.0
  http_cache_hive_store: ^5.0.2
  intl: any
  json_annotation: ^4.11.0
  native_dio_adapter: ^1.5.1
  path_provider: ^2.1.5
  riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.1
  freezed: ^3.2.5
  json_serializable: ^6.13.0
  riverpod_generator: ^4.0.3
  flutter_native_splash: ^2.4.7
  mockito: ^5.6.3

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env
    - assets/magikarp.png
    - assets/coming-soon-illustration-light-mode.png
    # Elements icons
    - assets/icons/bug.svg
    - assets/icons/category.svg
    - assets/icons/dark.svg
    - assets/icons/dragon.svg
    - assets/icons/electric.svg
    - assets/icons/fairy.svg
    - assets/icons/fighting.svg
    - assets/icons/fire.svg
    - assets/icons/flying.svg
    - assets/icons/ghost.svg
    - assets/icons/grass.svg
    - assets/icons/ground.svg
    - assets/icons/height.svg
    - assets/icons/ice.svg
    - assets/icons/normal.svg
    - assets/icons/poison.svg
    - assets/icons/pokeball.svg
    - assets/icons/psychic.svg
    - assets/icons/rock.svg
    - assets/icons/steel.svg
    - assets/icons/water.svg
    - assets/icons/weight.svg
    # Other icons
    - assets/icons/house.svg
    - assets/icons/heart.svg
    - assets/icons/user.svg
    - assets/icons/globe.svg
    - assets/icons/search.svg
    - assets/icons/male.svg
    - assets/icons/female.svg
    # Pokéball illustration, used in the splash screen
    - assets/splash/pokeball.svg
    # All elements illustrations
    - assets/elements/bug.svg
    - assets/elements/dark.svg
    - assets/elements/dragon.svg
    - assets/elements/electric.svg
    - assets/elements/fairy.svg
    - assets/elements/fighting.svg
    - assets/elements/fire.svg
    - assets/elements/flying.svg
    - assets/elements/ghost.svg
    - assets/elements/grass.svg
    - assets/elements/ground.svg
    - assets/elements/ice.svg
    - assets/elements/normal.svg
    - assets/elements/poison.svg
    - assets/elements/psychic.svg
    - assets/elements/rock.svg
    - assets/elements/steel.svg
    - assets/elements/water.svg
    # Onboarding illustrations
    - assets/onboarding/hilda-dark-mode.svg
    - assets/onboarding/hilda-light-mode.svg
    - assets/onboarding/kid-doctor-dark-mode.svg
    - assets/onboarding/kid-doctor-light-mode.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
          style: italic
          weight: 100

        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
          style: italic
          weight: 200

        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          style: italic
          weight: 300
        
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
          weight: 400
        
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          style: italic
          weight: 500
        
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          style: italic
          weight: 600
        
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          style: italic
          weight: 700

        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          style: italic
          weight: 800

        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
          style: italic
          weight: 900