enum PokemonElement {
  bug,
  dark,
  dragon,
  electric,
  fairy,
  fighting,
  fire,
  flying,
  ghost,
  grass,
  ground,
  ice,
  normal,
  poison,
  psychic,
  rock,
  steel,
  water;

  static PokemonElement fromString(String value) => switch (value) {
    'bug' => bug,
    'dark' => dark,
    'dragon' => dragon,
    'electric' => electric,
    'fairy' => fairy,
    'fighting' => fighting,
    'fire' => fire,
    'flying' => flying,
    'ghost' => ghost,
    'grass' => grass,
    'ground' => ground,
    'ice' => ice,
    'normal' => normal,
    'poison' => poison,
    'psychic' => psychic,
    'rock' => rock,
    'steel' => steel,
    'water' => water,
    _ => throw ArgumentError('Unknown PokemonType: $value'),
  };
}